name: first workflow

on:
  workflow_dispatch:
  
jobs:
  firstjob:
    runs-on: self-hosted
    steps:
      - name: firstjob-script
        shell: sh
        run: echo Hello World! This is the first job
        
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: secondJOb script
        shell: bash
        run: |
          echo this is thie second job
          echo and this is a multi line script
          
